site_name: Project KindleTeca
nav:
  - Home: 'index.md'
  - Business: 'business.md'
  - Corporate: 'corporate.md'
  - China: 'china.md'
  - Finance: 'finance.md'
  - Human: 'human.md'  
  - People: 'people.md'
  - Political: 'political.md'  
  - Startup: 'startup.md'
  
theme:
  name: material
  locale: en
  logo: 'https://raw.githubusercontent.com/renatobrf/kindle-teca/main/docs/icons/base-icon-small.png'
  favicon: 'https://raw.githubusercontent.com/renatobrf/kindle-teca/main/docs/favicon.ico'
  prev_next_buttons_location: none  
  extra_css:
    - stylesheets/extra.css
  icon_links:
    - name: GitHub
      url: ''
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.path
    - navigation.tracking
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
