site_name: KindleTeca on Renatobrf repo
nav:
  - Home: 'index.md'
  - Business: 'business.md'
  - Corporate: 'corporate.md'
  - China: 'china.md'
  - Human: 'human.md'
  - Generic: 'generic.md'
  - Startup BR: 'startup_br.md'
  - Contacts: 'contacts.md'
  
theme:
  name: readthedocs
  logo: 'https://raw.githubusercontent.com/renatobrf/kindle-teca/main/docs/icons/base-icon-small.png'
  favicon: 'https://raw.githubusercontent.com/renatobrf/kindle-teca/main/docs/favicon.ico'
  icon_links:
    - name: GitHub
      url: ''
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.path
    - navigation.tracking
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
